# Generated by Django 5.0 on 2025-04-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_asked_review_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='asked_review',
        ),
        migrations.AddField(
            model_name='ticket',
            name='asked_review',
            field=models.BooleanField(default=False),
        ),
    ]
