# Generated by Django 5.0 on 2025-04-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_asked_review_ticket_asked_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
