# Generated by Django 5.2.1 on 2025-05-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_userfollows_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='asked_review',
        ),
    ]
